Chia-Network/chia-network.github.io

README.md, _data/languages.yml, _data/strings.yml, collections/_advisors/04-gene.en.md, collections/_advisors/05-john.en.md, collections/_team/03-gene.en.md, jp/about/index.md, jp/blog/index.md, jp/community/index.md, jp/faq/index.md, jp/greenpaper/index.md, jp/index.md, jp/news/index.md
'better than Bitcoin' references. Update Advisors and Execs
=> Updated README.md. Fixed .jp by moving to .jp and adding .cn. Removed

_config.yml, _data/strings.yml, _includes/head.html
Add translations, fix google analytics config.
=> Add translations

_data/strings.yml, _layouts/download.html, _sass/download.scss
Update parts of the translations.
=> Update copy/make layout tweaks - home - about

README.md, _data/strings.yml, _layouts/post.html, _sass/download.scss, _sass/post.scss, collections/_posts/2018-06-11-the-asic-resistance-of-proof-of-space.en.md, collections/_posts/2018-11-07-chia-vdf-competition-guide.en.md, collections/_posts/2019-01-17-chia-vdf-competition-round-1-results-and-announcements.en.md, collections/_posts/2019-03-25-building-a-sustainable-blockchain-with-your-help.en.md, collections/_posts/2019-04-04-chia-network-announces-second-vdf-competition-with-in-total-prize-money.en.md, collections/_posts/2019-07-07-chia-network-announces-pos-competition.en.md, collections/_posts/2019-07-17-bram-twit-tv-interview.en.md, collections/_posts/2019-07-18-chia-vdf-competition-round-2-results-and-announcements.en.md, collections/_posts/2019-11-26-alpha-release.en.md, collections/_posts/2019-11-27-chialisp.en.md
* Make download header look better on tiny screens - I have a small phone and some text is cut off on the homepage.
* Add author next to blog post (this is a markdown field - links, text styling, and so on is supported). I added this field to all existing blog posts, and put Ali as the default author.
* Add Portuguese translations - they were missing earlier!
These changes are live at https://staging.hypotenuse.ca - you may need to hard refresh (Ctrl + F5 or Command + F5) to see the CSS changes though.
=> Site tweaks

_data/strings.yml
Conform to ppt and tweak community language
=> Tweak contributor description and conform to  PPT

collections/_posts/2019-03-25-building-a-sustainable-blockchain-with-your-help.en.md, collections/_posts/2019-04-04-chia-network-announces-second-vdf-competition-with-in-total-prize-money.en.md
Getting closer to accurate credits
=> Update blog authors

Gemfile, Gemfile.lock, _config.yml, index.md, releases/index.md
Redirects /developer to /download/home and /errata to /releases
=> Redirect /developer and /errata

index.md, releases/index.md
redirects should be /errata/ only which catches both /errata and /errata/
=> Correct redirects, slash only

_includes/email_box.html, _layouts/contact.html, _layouts/download.html, _sass/contact.scss, _sass/email_box.scss, css/main.scss
- fix download page wrapping order
- add mailing list to download page
- move mailing list on contact page
=> UI Updates

_layouts/download.html
=>  Fix download page alignment

collections/_posts/2021-02-22-plotting-basics.md
Updated k32 temp space values from 332 GiB to 269 GiB and updated the RAM chart with @pyl's findings.
=> Updated temp space and RAM 

collections/_posts/2021-05-24-SSD-endurance.md
new blog post on SSD endurance
=> adding endurance page

collections/_posts/2021-05-24-SSD-endurance.md
=> formatting

collections/_posts/2021-06-13-AMA-plotting-speed-and-security-in-chia.md, collections/_posts/2021-06-15-common-misconceptions-vol-1.md
added post and edited June 13 AMA post for a typo
=> Misconceptions v1 post

collections/_posts/2021-06-15-common-misconceptions-vol-1.md
sargonas found some more edits
=> more edits

_layouts/download.html
https://automatic-bassoon-80648a5c.pages.github.io/download/
=> Windows disclaimer

_layouts/careers.html
More than 1 career listing was breaking formatting on mobile
=> changed width style for current openings formatting

collections/_posts/2021-08-11-chia-cultivation-grant-program.md
https://twitter.com/13otnet/status/1428022069728407557
=> fix a couple typos on the cultivation grant blog post

collections/_posts/2021-08-11-chia-cultivation-grant-program.md
added FAQ, updated date, and gramma/typo updates with latest information changes
=> Grants blog updates

collections/_posts/2021-08-11-chia-cultivation-grant-program.md
a grammar thing and some typo/punctuation
=> small edits

collections/_posts/2021-08-30-chia-joins-the-open-compute-project.md
Images in OCP post weren't resizing on mobile
=> fixed post images for mobile

.gitignore, _layouts/download.html
=> add links to beta installers

_layouts/download.html
=> add beta notes

_data/strings.yml, _layouts/about.html, collections/_faq/29-guidelines.en.md
Updated the Faq and About pages
=> feat: update faq and about

_includes/navigation.html, img/menuBarIcon.svg
Fixed the menu button on mobile view.
=> feat: fixed menu button on mobile

_includes/navigation.html, _sass/homemain.scss
Corrected style for menu button
=> fix: corrected menu button style

_layouts/grants.html
=> grants page faq fix

.nova/Configuration.json, Gemfile.lock, _layouts/profile.html, profiles/bram-cohen/index.md, profiles/gene-hoffman/index.md, profiles/misha-graboi/index.md
Note that the LinkedIn usernames don't seem to be recognized.
=> Add twitter and linkedin for C folks

profiles/ali-shadle/index.md
Edit Ali's profile to reflect that she is VP of Operations. The title currently on display seems more in tune with Bram's function.
=> Edit Ali's title

_layouts/homemain.html
"soon to be" was bugging me and I wrote it so...
=> Simplify "future of markets"

collections/_job_descriptions/05-cypress-qa-engineer.md
=> adding qa engineer role

collections/_job_descriptions/06-release-manager.md
=> release manager role

collections/_posts/2021-12-21-happy-holidays-from-chia.en.md
=> Holiday edits

_data/strings.yml, _includes/accordion.html, _includes/navigation.html, _layouts/buy-xch.html, _layouts/offers.html, _sass/offers.scss, buy-xch/index.md, collections/_faq/15-can-i-buy-chia-today.en.md, collections/_faq/16-how-can-I-buy-Chia.en.md, css/main.scss, offers/index.md
- Buy XCY page
- Offers page
- faq update
=> Buy XCH and Offers

collections/_news/2022-01-12-businesswire.md, collections/_posts/2022-01-12-chia-offers-are-here-en.md
- added news item
- fixed typo
=> added offers news item

_layouts/stably.html
of course there was one more thing
=> removed a period

README.md, _layouts/homemain.html
- new slide
- removed "Test" in README
=> buy xch slide 

_layouts/careers.html
replaced old Jekyll style careers page with greenhouse.io embed
=> added greenhouse to careers page

_layouts/download.html
* updated beta wallet download text
* new installers
=> Wallet beta

_sass/blog.scss
=> fixed blog formatting issue

README.md
Added instructions to README on how to set when a post gets published.
=> post date and time publishing

collections/_news/2022-02-22-bloomberg-wbg.md, collections/_news/2022-03-17-capital-com.md, collections/_news/2022-05-18-businesswire.md
* Bloomberg story
* Businesswire story
=> Add news items

_layouts/blockchain-valuation-model.html
This updates the language generally. Capitalization is somewhat all over the place so this probably needs one last close look in another PR to harmonize that.
=> Language updates

_layouts/blockchain-valuation-model.html, collections/_posts/2022-06-08-valuing-blockchains.en.md
updated coin model intro and blog post footnotes
=> Coin model intro update

collections/_posts/2022-07-25-upgrading-the-cat-standard.en.md
=> CAT2 blog update

_layouts/grants.html, collections/_posts/2022-08-08-announcing-bladebit-2.en.md, collections/_posts/2022-08-17-bringing-transparency-and-efficiency-to-carbon-markets.en.md
- added carbon blog post
- updated author links in a bladebit blog
- fixed wrong screenshot on grants page
=> added carbon blog and some site content fixes
